blackhole:
  address: localhost:8082
  celestial: localhost:8000
  apollo: localhost:8083 
  db:
    - 0.0.0.0:2379
  queue:
    myqueue1:
      namespace: mynamespace
      retry:
        delay: linear # [linear | exp ] -> interval * (doubling + attempt)
        doubling: 1 # increase wait on next retry
        limit: 50000 # try 5 times before go to 'sleep' and tocke bucket is not notify
      maxWorkers: 4 # max number of warkers to spawn
      capacity: 4 # capacity of token bucket, when full burst
      tokens: 0 # number of tokens to start
      fillInterval: # fill interval per time unit ex: 2/s two tokens added in one second
        interval: 1
        rate: s # [s/second | ms/milisecond | m/minute | h/hour]
    myqueue2:
      namespace: default
      retry:
        delay: exp # [linear | exp ]
        doubling: 2 # increase wait on next retry -> interval * (doubling ^ attempt)
        limit: 50000 # try 5 times before go to 'sleep' and tocke bucket is not notify
      maxWorkers: 5
      capacity: 5
      tokens: 0
      fillInterval:
        interval: 1
        rate: s # [s/second | ms/milisecond | m/minute | h/hour]
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/

# when config file is loaded, n+1 queues will be created (+1 is a default)
