blackhole:
  address: localhost:8081
  db:
    - localhost:7373
  queue:
    myqueue1:
      retry:
        delay: linear # [linear | exp ] -> interval * (doubling + attempt)
        doubling: 1 # increase wait on next retry
        limit: 5 # try 5 times before go to 'sleep' and tocke bucket is not notify
      maxWorkers: 4 # max number of warkers to spawn
      capacity: 4 # capacity of token bucket, when full burst
      tokens: 0 # number of tokens to start
      fillInterval: # fill interval per time unit ex: 2/s two tokens added in one second
        interval: 1
        rate: s # [s/second | ms/milisecond | m/minute | h/hour]
    myqueue2:
      retry:
        delay: exp # [linear | exp ]
        doubling: 2 # increase wait on next retry -> interval * (doubling ^ attempt)
        limit: 5 # try 5 times before go to 'sleep' and tocke bucket is not notify
      maxWorkers: 5
      capacity: 5
      tokens: 0
      fillInterval:
        interval: 2
        rate: ms # [s/second | ms/milisecond | m/minute | h/hour]

# when config file is loaded, n+1 queues will be created (+1 is a default)
